reload('user.plugins')
reload('user.colorscheme')
reload('user.options')
reload('user.keymaps')
reload('user.which-key')
reload('user.statusline')
reload('user.lsp')
reload('user.dashboard')
-- reload('user.lsp-status')
reload('user.autocmds')
reload('user.hop')
reload('user.hslens')
reload('user.neoscroll')
reload('user.scrollbar')
reload('user.undotree')
